### ISSUE TITLE
badlands error when used with UWGeo v2.9

### ISSUE THREAD

**Issue by raghugram** [badlands-model/badlands#13]
Hi

I am trying to run a simple 2D model given in UWGeodynamics tutorials(Tutorial_11), which illustrates the coupling between UWGeo and Badlands.

I am getting a Segmentation fault. Debug information shows
-----------------------------------------------------------------------------------
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007f0479a87cb5 in build (pyoids=..., pygids=..., pytx=..., pyty=..., pytedge=..., pytelmt=..., pyvx=..., pyvy=...,
pyvedge=..., pyvarea=..., pyngbs=..., pyvlenght=..., pydlenght=...,
pymaxngbh=<error reading variable: Cannot access memory at address 0x1ef670001ef68>,
pygnodes=<error reading variable: Cannot access memory at address 0x0>, pyonodes=5, pydnodes=3, pydedges=3,
pydelems=69455, pyvnodes=69455, pyvedges=69455) at utils/fvframe.f90:11
11 utils/fvframe.f90: No such file or directory.
------------------------------------------------------------------------------------
I cloned from package Github and ran setup.py to install. so the version is 2.0.13

I can confirm the code branch pyBadlands_serial with UWGeo is working fine.
And I see since June 2019, there have been a lot of changes and I suspect that is why this issue occured?

**Comment by tristan-salles** [comment]
Hi @raghugram it looks like the code cannot find the utils directory. Have you tried to run a badlands model without the UWGeo coupling, e.g. one of the examples in the examples or workshop directory and did you have the same error message. You can also try to use the pip install badlands package...

**Comment by raghugram** [comment]
Hi @tristan-salles  
1) I tried installing using pip and also git clone and install,in both installations, the utils directory is not created in the installed directory. I manually copied the utils folder(with object files and .mod files) into the installation.
Now the same segmentation error props up but WITHOUT the "No such file or directory for _utils_ "error.

2) I tried running the examples in workshop, they seem to run fine.

**Comment by tristan-salles** [comment]
Hi @raghugram,

If both underworld and badlands are working fine by themselves then there should not be any issues like the ones you are reporting for badlands as the library will know how and where to find the object and module files. You also should not have to copy the **utils** folder into the installation one... It should be done automatically. 

Did you have to do this to run the examples in the workshop folder? Which OS are you using to run the coupled models?

**Comment by raghugram** [comment]
Hi,

I dont know what I am doing wrong here.

I got the UWGeo docker and in the docker I tried to run badlands.

Now, I got badlands docker container as given in badlands.readthedocs.io and then installed UWGeo in the container and I get the same error.

Since its docker, its the debian distribution of Linux that came default with docker container.

**Comment by tristan-salles** [comment]
Hi @raghugram,

You should try to load the docker container available from from underworldcode called uwgeodynamics the following versions: 2.7.1, 2.7.7 or  v2.8.1 Have both underworld and badlands installed already and should be working for you as well.

**Comment by raghugram** [comment]
Hi Tristan-Salles,
Sorry for the delay.
Its the serial version of badlands and it's working. I close this issue for now.
