### ISSUE TITLE
readEroLay type error & boundary types

### ISSUE THREAD

**Issue by eslrgs** [badlands-model/badlands#18]
Hi,

I have made both topography and uplift fields that work within my model, however when I make an erodibility field using the same method and try to read using readEroLay I get a `'NoneType' object cannot be interpreted as an integer` error. I have tried to fix it but cannot seem to get round the problem. Everything else has been working perfectly!

I have cross-checked the erodibility csv with the Corinth example and it is of the same structure.

Also, is there any information on the differences between the boundary types (flat, slope, fixed or wall)?

Thanks,

eslrgs

<img width="730" alt="Screenshot 2020-06-19 at 13 55 28" src="https://user-images.githubusercontent.com/33627729/85134916-1f845b00-b235-11ea-9122-9caa210ac732.png">

**Comment by tristan-salles** [comment]
Hi @eslrgs, I think you first need to run the following function before loading the erodibility maps: `forcings.readDEM('data/nodes.csv')`
So it will look like:

`forcings = rInput.readInput()`
`forcings.readDEM('data/nodes.csv')`
`forcings.readEroLay('data/ero.csv')`


Regarding the boundary types:
+ flat: use the edges elevation values to define boundary elevation
+ slope: use the slope on the edges to define boundary elevation
+ fixed: use initial elevation of the edges to  define boundary elevation
+ wall: create a wall (like for a flume tank)

Most of the time you want to use the slope of flat boundary types.

Hope it helps!
Tristan

**Comment by eslrgs** [comment]
That's the fix - thanks Tristan! All working now.

Thanks for the boundary information too.

**Comment by eslrgs** [comment]
One final question..

Are the diffusion values within the XML input per year or per time-step? i.e. does a marine diffusion rate of 0.0001 m2/yr within a model using a timestep of 10000 years = 1 m2/a within the XML input?

**Comment by tristan-salles** [comment]
The value is per year: 
https://badlands.readthedocs.io/en/latest/xml.html#hillslope-structure
