### ISSUE TITLE
a minor bug in forceSim.py causing TypeError

### ISSUE THREAD

**Issue by SueeChan** [badlands-model/badlands#19]
Hi all, 

I turned on the erodibility structure for my Badlands model and realize a minor bug in forceSim.py which causes TypeError. 

In line 801 and 820, a function `.shape()` is called for a tuple object `Ke`, where the attribute `.shape` should be gotten instead. 

line 801: `lay = Ke.shape()[1]`
line 820:` lay = Ke.shape()[1]`

Thanks for your attention!

Regards,
Sue

**Comment by tristan-salles** [comment]
Thanks Sue for finding this bug! You rock! I will update it in the next version of badlands
