### ISSUE TITLE
Error in load_xml with latest meshplex version

### ISSUE THREAD

**Issue by sebhaan** [badlands-model/badlands#23]
Where: Installation of Badlands via PyPI (by default latest meshplex version installed: 0.16.0)
Error in model.load_xml(...)

```bash
~/anaconda/envs/py38_badlands/lib/python3.8/site-packages/badlands/surface/FVmethod.py in _FV_utils(self, l GIDs, verbose)
     81         if meshplex.__version__>= "0.14.0":
     82             edges_nodes = Tmesh.edges["points"]
---> 83             cells_nodes = Tmesh.cells["points"]
     84             cells_edges = Tmesh.cells["edges"]
     85         else:

TypeError: 'method' object is not subscriptable
```

Temporary working solution: Downgrade meshplex to version==0.14.0 (no error)

Suggested solution: specify working version of meshplex in requirements.txt or add new version if-case in FVmethod.py

**Comment by tristan-salles** [comment]
Hi @sebhaan thanks for reporting the issue with the latest version of meshplex. I have upgraded badlands to account for the changes with meshplex new release. Cheers!
