### ISSUE TITLE
Error in live demo using binder

### ISSUE THREAD

**Issue by gaowqspace** [badlands-model/badlands#29]
when I run the live demo, I met the error:

Spawn failed: Server at http://10.0.149.232:8888/user/badlands-model-badlands-docker-zaja2h9c/ didn't respond in 30 seconds

I don't install juypter notebook on my pc, should install it firstly?
How can I solve it and run the live demo?

thank you

**Comment by tristan-salles** [comment]
Best option would be to use the docker container that requires minimal installation:
https://badlands.readthedocs.io/en/latest/install.html#docker

**Comment by gaowqspace** [comment]
> Best option would be to use the docker container that requires minimal installation: https://badlands.readthedocs.io/en/latest/install.html#docker

Thanks for your reply！
I have installed it on Ubuntu 20.04 by Docker. But I need to deploy it on my windows development environment. 
Can you give me some advice about this?

Thank you!

**Comment by tristan-salles** [comment]
Hi @gaowqspace 

I am not super familiar with Windows systems but you should be able to install docker desktop for Windows and then use the same repository as the one you've installed on your Ubuntu machine.

**Comment by gaowqspace** [comment]
> Hi @gaowqspace
> 
> I am not super familiar with Windows systems but you should be able to install docker desktop for Windows and then use the same repository as the one you've installed on your Ubuntu machine.

Thank you！I will try it.
