### ISSUE TITLE
Error in install

### ISSUE THREAD

**Issue by jmk95Liverpool** [badlands-model/badlands#31]
Hi, 

I am currently trying to install the Badlands python package onto my desktop. I keep receiving the error message below:
 
Collecting badlands
  Using cached badlands-2.2.3.tar.gz (185 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\jmk95\AppData\Local\Temp\pip-install-b42xdva9\badlands_f62436b63cee46798ca09046df7d0d71\setup.py", line 24, in <module>
          subprocess.call(["make", "-C", "utils"])
        File "C:\Anaconda3\2022.05\lib\subprocess.py", line 349, in call
          with Popen(*popenargs, **kwargs) as p:
        File "C:\Anaconda3\2022.05\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Anaconda3\2022.05\lib\subprocess.py", line 1420, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

All dependencies are installed and up to date.  
I am running conda as an admin as well, so it doesn't seem to be a permissions issue?
I have manually reinstalled set up tools and pip: they are both up to date. 
I can install other python packages - including the Badlands companion package from the same source

Any help would be greatly appreciated.

**Comment by tristan-salles** [comment]
Hi there,

The pip package hasn't been made for windows and I think this is why you are receiving this error message. 

What you can do is to install it from the source. To do so, first open your anaconda environment where you have all the dependencies install then clone badlands & badlands-companion using git:

```bash
git clone https://github.com/badlands-model/badlands.git
git clone https://github.com/badlands-model/badlands-companion.git
```
cd to the respective folder and run the install command:
```bash
cd badlands/badlands
python3 setup.py install --user
cd ../../badlands-companion
python3 setup.py install --user
```

**Comment by jmk95Liverpool** [comment]
Hi,

Thanks for that - any idea why it's only badlands (not badlands companion or any other module) that has this issue?

James


_
James Lovell-Kennedy
Geologist
He/Him
_

QUEST Research Group
Department of Earth, Ocean and Ecological Sciences | University of Liverpool
_

Researchgate<https://www.researchgate.net/profile/James-Lovell-Kennedy> | LinkedIn<https://www.linkedin.com/in/james-lovell-kennedy/>
________________________________

**Comment by tristan-salles** [comment]
I think it because badlands is not pure Python and has some pre-compiled code in its pip package.

**Comment by jmk95Liverpool** [comment]
Sorry - now I'm getting this error trying to run the basin example:
ImportError: cannot import name 'fvframe' from partially initialized module 'badlands'

**Comment by tristan-salles** [comment]
Not sure, did it complain during compilation? maybe python3 setup.py install works.

**Comment by hakertop** [comment]
(mybadlands) E:\PhD\BadlandsGit\badlands>python setup.py install --user
Traceback (most recent call last):
  File "E:\PhD\BadlandsGit\badlands\setup.py", line 24, in <module>
    subprocess.call(["make", "-C", "utils"])
  File "D:\ProgramData\anaconda3\envs\mybadlands\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\ProgramData\anaconda3\envs\mybadlands\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\ProgramData\anaconda3\envs\mybadlands\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。


Still not have the same error. All dependencies are installed

**Comment by tristan-salles** [comment]
The pip packages have been compiled for Mac and Linux OS only so it does make sense that they would not work under windows.

For windows you would need to install it from the source. I have uploaded a a yaml environment file in the master branch so the first thing would be to clone again the badlands repository from GitHub.

To make the environment do:
`conda env create --file environment.yml`

This should create the environment called **badlands**, activate it:
`conda activate gospl`

Then navigate to badlands repository and:
`python3 setup.py install --user`

Regarding the **badlands-companion**, I guess this is the same issue, there isn’t a windows package. So you will need to proceed with above  install command. The tribad package is found here: https://github.com/Geodels/tribad
