### ISSUE TITLE
How to visualize the coupling results of  Badland and UWgeodynamics in Paraview?

### ISSUE THREAD

**Issue by Ankke3** [badlands-model/badlands#39]
Hi guys,

I want to visualize the result of tutorial 11 of Uwgeodynamic, but the Badlands surfaces are 2D. How to obtain a 3D surface in Paraview.

Thanks!

**Comment by tristan-salles** [comment]
@julesghub might be able to help on this one.... are you trying to visualise it in Paraview? Maybe you need to change the view to a 3D surface.

**Comment by Ankke3** [comment]
> @julesghub might be able to help on this one.... are you trying to visualise it in Paraview? Maybe you need to change the view to a 3D surface.

Thanks for your reply, I have tried to visualise it in Paraview, but it looks like two planes are spliced together. I will try to change the view mode.
