### ISSUE TITLE
Who can install this program sucessfully?

### ISSUE THREAD

**Issue by hakertop** [badlands-model/badlands#40]
Hi All,

Can someone install this program successfully via PyPI package. I can't do it successfully even if according to the instructions on the website (https://pypi.org/project/badlands/). I worked with my friends but it didn't work. I created a new environment via Anaconda and want to install the badlands, it is very hard.

Then I used the Docker. Although it can run, the program always shows that the kernel is dead. That makes me crazy.

Do someone meet the same problems? Could the author make a video to show how to install this program via PyPI?

I feel this program is very good to simulate the landscape evolution. However, how to install it is very hard.

All the best,
Yangen 

![QQ图片20240410121044](https://github.com/badlands-model/badlands/assets/55942841/5ed627bb-cde9-4570-8d1c-beab8ebaa8d3)

**Comment by tristan-salles** [comment]
The pip packages have been compiled for Mac and Linux OS only so it does make sense that they would not work under windows.

For windows you would need to install it from the source. I have uploaded a a yaml environment file in the master branch so the first thing would be to clone again the badlands repository from GitHub.

To make the environment do:
`conda env create --file environment.yml`

This should create the environment called **badlands**, activate it:
`conda activate gospl`

Then navigate to badlands repository and:
`python3 setup.py install --user`

Regarding the **badlands-companion**, I guess this is the same issue, there isn’t a windows package. So you will need to proceed with above  install command. The tribad package is found here: https://github.com/Geodels/tribad

**Comment by XuesongDing** [comment]
Hi Yangen, 

I am happy to help if you still encounter errors. Feel free to reach out through email to xuesong.ding@beg.utexas.edu. 

Cheers,
Xuesong

**Comment by hakertop** [comment]
Hi Xuesong,



Thanks for your response! I still try to install it today. Unfortunately, it doesn't work!


Do you speak Chinese? or do you use Chinese social APP likes Wechat(微信)? My Wechat account is ''hakertop".


I will send another English email next  to describe more details if you don't use the Wechat!


All the best,


Yangen
Nanjing Normal Univerisity 






| |
Yangen Shen
|
|
***@***.***
|
---- Replied Message ----
| From | Xuesong ***@***.***> |
| Date | 4/10/2024 22:02 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [badlands-model/badlands] Who can install this program sucessfully? (Issue #40) |

Hi Yangen,

I am happy to help if you still encounter errors. Feel free to reach out through email to ***@***.***

Cheers,
Xuesong
