### ISSUE TITLE
some prombles in strile slip example

### ISSUE THREAD

**Issue by zhifengmuyun** [badlands-model/badlands#42]
Hi. I want to simulate the shape of the river's way under the influence of  the strike slip fault so that I 'm studying the strike slip example. But I don't know how to set the position  and velocity of the  fault. In fact I want to know how does the file 'node.csv' and 'uplift0.csv' generate(As I want to create my own parameters) and what's the meaning of the numbers of each column in these two files.

**Comment by tristan-salles** [comment]
Hi there, 

The file node.csv is a regular grid [(see)](https://badlands.readthedocs.io/en/latest/xml.html) with the xyz coordinates in metres. If you have installed the badlands companion (or are using the docker image) you can look at a simple example like this [one](https://github.com/badlands-model/badlands-workshop/blob/master/workshop/basin/runBadlands.ipynb).

The tectonic [file](https://badlands.readthedocs.io/en/latest/xml.html#tectonic-structure) provides the displacements in metres along the 3 directions (X,Y and Z). Those displacements are associated to the coordinates defined in the node.csv file. In other words, the first coordinates (i.e. first line) in node.csv will be moving based on the displacements in the first line in the uplift0.csv over the period defined by the parameters <dstart> and <dend>.
